using System.Reflection;

namespace PingTunnelVPN.App;

/// <summary>
/// Application metadata information.
/// This file is auto-generated by the build script.
/// </summary>
public static class AppInfo
{
    /// <summary>
    /// Gets the application name.
    /// </summary>
    public static string Name => "PingTunnel - VPN Client";

    /// <summary>
    /// Gets the application version.
    /// </summary>
    public static string Version => "1.0.1";

    /// <summary>
    /// Gets the GitHub repository URL.
    /// </summary>
    public static string GitHubUrl => "https://github.com/DrSaeedHub/PingTunnel-VPN-Client";

    /// <summary>
    /// Gets the application version from the assembly.
    /// </summary>
    public static string AssemblyVersion
    {
        get
        {
            var assembly = Assembly.GetExecutingAssembly();
            var version = assembly.GetName().Version;
            return version?.ToString() ?? Version;
        }
    }
}
